#!/bin/bash

#SBATCH --account=nn4654k
#SBATCH --mail-type=None
#SBATCH --job-name=AgF
#SBATCH --output=AgF.log
#SBATCH --error=AgF.err
#SBATCH --time=00-12:00:00
#SBATCH --nodes=6
#SBATCH --ntasks-per-node=12

module purge
module load Python/3.9.6-GCCcore-11.2.0
module load OpenMPI/4.1.1-GCC-11.2.0

cp AgF.inp $SCRATCH
cd $SCRATCH
export OMP_NUM_THREADS=15
/cluster/home/ambr/mrchem/install_upstream_master/bin/mrchem --launcher 'mpirun --rank-by node --map-by numa --bind-to numa --oversubscribe' --json AgF

savefile AgF.out
savefile AgF.json

DIR=/cluster/projects/nn4654k/$(whoami)/MWOrbitals/${SLURM_JOBID}
mkdir -p $DIR
cp orbitals/* $DIR/
echo $DIR > ${SLURM_SUBMIT_DIR}/AgF.orbitals

DIR=/cluster/projects/nn4654k/$(whoami)/MWCheckpoints/${SLURM_JOBID}
mkdir -p $DIR
cp checkpoint/* $DIR/
echo $DIR > ${SLURM_SUBMIT_DIR}/AgF.checkpoint

exit 0