#! /bin/bash

#-------------------------------------------
# File generated 2021-05-08 22:03:21.581240
#-------------------------------------------

#SBATCH --account=nn9330k
#SBATCH --job-name=H2O
#SBATCH --output=H2O.log
#SBATCH --error=H2O.err
#SBATCH --nodes=4
#SBATCH --ntasks-per-node=8
#SBATCH --cpus-per-task=16
#SBATCH --time=60:00
#SBATCH --mail-type=NONE
#SBATCH --partition=normal

source /cluster/home/ambr/mrchem/tools/betzy.env
export OMP_NUM_THREADS=16

set -o errexit
set -o nounset

cp H2O.inp $SCRATCH
cp -r /cluster/projects/nn9330k/ambr/orbitals/181727 $SCRATCH/initial_guess

cd $SCRATCH
/cluster/home/ambr/mrchem/install-new-zora/bin/mrchem --launcher='mpirun -map-by ppr:1:numa -bind-to numa' H2O

savefile H2O.out
savefile H2O.json

mkdir -p /cluster/projects/${SLURM_JOB_ACCOUNT}/ambr/orbitals/${SLURM_JOBID}
cp orbitals/* /cluster/projects/${SLURM_JOB_ACCOUNT}/ambr/orbitals/${SLURM_JOBID}/
echo /cluster/projects/${SLURM_JOB_ACCOUNT}/ambr/orbitals/${SLURM_JOBID} > ${SLURM_SUBMIT_DIR}/H2O.orbitals

mkdir -p /cluster/projects/${SLURM_JOB_ACCOUNT}/ambr/checkpoints/${SLURM_JOBID}
cp checkpoint/* /cluster/projects/${SLURM_JOB_ACCOUNT}/ambr/checkpoints/${SLURM_JOBID}/
echo /cluster/projects/${SLURM_JOB_ACCOUNT}/ambr/checkpoints/${SLURM_JOBID} > ${SLURM_SUBMIT_DIR}/H2O.checkpoint

exit 0
