#!/bin/bash

#SBATCH --account=nn4654k
#SBATCH --mail-type=None
#SBATCH --job-name=SrH
#SBATCH --output=SrH.log
#SBATCH --error=SrH.err
#SBATCH --time=00-10:00:00
#SBATCH --nodes=8
#SBATCH --ntasks-per-node=12

module purge
module load Python/3.9.6-GCCcore-11.2.0
module load OpenMPI/4.1.1-GCC-11.2.0

cp SrH.inp $SCRATCH
cd $SCRATCH
cp -r /cluster/projects/nn4654k/ambr/MWOrbitals/348838 initial_guess
export OMP_NUM_THREADS=15
/cluster/home/ambr/mrchem/install_upstream_master/bin/mrchem --launcher 'mpirun --rank-by node --map-by numa --bind-to numa --oversubscribe' --json SrH

savefile SrH.out
savefile SrH.json

DIR=/cluster/projects/nn4654k/$(whoami)/MWOrbitals/${SLURM_JOBID}
mkdir -p $DIR
cp orbitals/* $DIR/
echo $DIR > ${SLURM_SUBMIT_DIR}/SrH.orbitals

DIR=/cluster/projects/nn4654k/$(whoami)/MWCheckpoints/${SLURM_JOBID}
mkdir -p $DIR
cp checkpoint/* $DIR/
echo $DIR > ${SLURM_SUBMIT_DIR}/SrH.checkpoint

exit 0