#!/bin/bash

#SBATCH --account=nn4654k
#SBATCH --mail-type=None
#SBATCH --job-name=Nb_pbe
#SBATCH --output=Nb_pbe.log
#SBATCH --error=Nb_pbe.err
#SBATCH --time=00-20:00:00
#SBATCH --partition=bigmem
#SBATCH --mem-per-cpu=10GB
#SBATCH --ntasks=40
#SBATCH --cpus-per-task=4

module purge
module load intel/2019b
module load OpenMPI/3.1.4-GCC-8.3.0
module load Python/3.7.4-GCCcore-8.3.0

cp Nb_pbe.inp $SCRATCH
cp /cluster/projects/nn4654k/ambr/zora/row5/calcs_gto/Nb_ano-r3_pbe_cubes/phi_a_scf_0_re.cube $SCRATCH
cp /cluster/projects/nn4654k/ambr/zora/row5/calcs_gto/Nb_ano-r3_pbe_cubes/phi_a_scf_10_re.cube $SCRATCH
cp /cluster/projects/nn4654k/ambr/zora/row5/calcs_gto/Nb_ano-r3_pbe_cubes/phi_a_scf_11_re.cube $SCRATCH
cp /cluster/projects/nn4654k/ambr/zora/row5/calcs_gto/Nb_ano-r3_pbe_cubes/phi_a_scf_12_re.cube $SCRATCH
cp /cluster/projects/nn4654k/ambr/zora/row5/calcs_gto/Nb_ano-r3_pbe_cubes/phi_a_scf_13_re.cube $SCRATCH
cp /cluster/projects/nn4654k/ambr/zora/row5/calcs_gto/Nb_ano-r3_pbe_cubes/phi_a_scf_14_re.cube $SCRATCH
cp /cluster/projects/nn4654k/ambr/zora/row5/calcs_gto/Nb_ano-r3_pbe_cubes/phi_a_scf_15_re.cube $SCRATCH
cp /cluster/projects/nn4654k/ambr/zora/row5/calcs_gto/Nb_ano-r3_pbe_cubes/phi_a_scf_16_re.cube $SCRATCH
cp /cluster/projects/nn4654k/ambr/zora/row5/calcs_gto/Nb_ano-r3_pbe_cubes/phi_a_scf_17_re.cube $SCRATCH
cp /cluster/projects/nn4654k/ambr/zora/row5/calcs_gto/Nb_ano-r3_pbe_cubes/phi_a_scf_18_re.cube $SCRATCH
cp /cluster/projects/nn4654k/ambr/zora/row5/calcs_gto/Nb_ano-r3_pbe_cubes/phi_a_scf_19_re.cube $SCRATCH
cp /cluster/projects/nn4654k/ambr/zora/row5/calcs_gto/Nb_ano-r3_pbe_cubes/phi_a_scf_1_re.cube $SCRATCH
cp /cluster/projects/nn4654k/ambr/zora/row5/calcs_gto/Nb_ano-r3_pbe_cubes/phi_a_scf_20_re.cube $SCRATCH
cp /cluster/projects/nn4654k/ambr/zora/row5/calcs_gto/Nb_ano-r3_pbe_cubes/phi_a_scf_21_re.cube $SCRATCH
cp /cluster/projects/nn4654k/ambr/zora/row5/calcs_gto/Nb_ano-r3_pbe_cubes/phi_a_scf_22_re.cube $SCRATCH
cp /cluster/projects/nn4654k/ambr/zora/row5/calcs_gto/Nb_ano-r3_pbe_cubes/phi_a_scf_2_re.cube $SCRATCH
cp /cluster/projects/nn4654k/ambr/zora/row5/calcs_gto/Nb_ano-r3_pbe_cubes/phi_a_scf_3_re.cube $SCRATCH
cp /cluster/projects/nn4654k/ambr/zora/row5/calcs_gto/Nb_ano-r3_pbe_cubes/phi_a_scf_4_re.cube $SCRATCH
cp /cluster/projects/nn4654k/ambr/zora/row5/calcs_gto/Nb_ano-r3_pbe_cubes/phi_a_scf_5_re.cube $SCRATCH
cp /cluster/projects/nn4654k/ambr/zora/row5/calcs_gto/Nb_ano-r3_pbe_cubes/phi_a_scf_6_re.cube $SCRATCH
cp /cluster/projects/nn4654k/ambr/zora/row5/calcs_gto/Nb_ano-r3_pbe_cubes/phi_a_scf_7_re.cube $SCRATCH
cp /cluster/projects/nn4654k/ambr/zora/row5/calcs_gto/Nb_ano-r3_pbe_cubes/phi_a_scf_8_re.cube $SCRATCH
cp /cluster/projects/nn4654k/ambr/zora/row5/calcs_gto/Nb_ano-r3_pbe_cubes/phi_a_scf_9_re.cube $SCRATCH
cp /cluster/projects/nn4654k/ambr/zora/row5/calcs_gto/Nb_ano-r3_pbe_cubes/phi_b_scf_0_re.cube $SCRATCH
cp /cluster/projects/nn4654k/ambr/zora/row5/calcs_gto/Nb_ano-r3_pbe_cubes/phi_b_scf_10_re.cube $SCRATCH
cp /cluster/projects/nn4654k/ambr/zora/row5/calcs_gto/Nb_ano-r3_pbe_cubes/phi_b_scf_11_re.cube $SCRATCH
cp /cluster/projects/nn4654k/ambr/zora/row5/calcs_gto/Nb_ano-r3_pbe_cubes/phi_b_scf_12_re.cube $SCRATCH
cp /cluster/projects/nn4654k/ambr/zora/row5/calcs_gto/Nb_ano-r3_pbe_cubes/phi_b_scf_13_re.cube $SCRATCH
cp /cluster/projects/nn4654k/ambr/zora/row5/calcs_gto/Nb_ano-r3_pbe_cubes/phi_b_scf_14_re.cube $SCRATCH
cp /cluster/projects/nn4654k/ambr/zora/row5/calcs_gto/Nb_ano-r3_pbe_cubes/phi_b_scf_15_re.cube $SCRATCH
cp /cluster/projects/nn4654k/ambr/zora/row5/calcs_gto/Nb_ano-r3_pbe_cubes/phi_b_scf_16_re.cube $SCRATCH
cp /cluster/projects/nn4654k/ambr/zora/row5/calcs_gto/Nb_ano-r3_pbe_cubes/phi_b_scf_17_re.cube $SCRATCH
cp /cluster/projects/nn4654k/ambr/zora/row5/calcs_gto/Nb_ano-r3_pbe_cubes/phi_b_scf_1_re.cube $SCRATCH
cp /cluster/projects/nn4654k/ambr/zora/row5/calcs_gto/Nb_ano-r3_pbe_cubes/phi_b_scf_2_re.cube $SCRATCH
cp /cluster/projects/nn4654k/ambr/zora/row5/calcs_gto/Nb_ano-r3_pbe_cubes/phi_b_scf_3_re.cube $SCRATCH
cp /cluster/projects/nn4654k/ambr/zora/row5/calcs_gto/Nb_ano-r3_pbe_cubes/phi_b_scf_4_re.cube $SCRATCH
cp /cluster/projects/nn4654k/ambr/zora/row5/calcs_gto/Nb_ano-r3_pbe_cubes/phi_b_scf_5_re.cube $SCRATCH
cp /cluster/projects/nn4654k/ambr/zora/row5/calcs_gto/Nb_ano-r3_pbe_cubes/phi_b_scf_6_re.cube $SCRATCH
cp /cluster/projects/nn4654k/ambr/zora/row5/calcs_gto/Nb_ano-r3_pbe_cubes/phi_b_scf_7_re.cube $SCRATCH
cp /cluster/projects/nn4654k/ambr/zora/row5/calcs_gto/Nb_ano-r3_pbe_cubes/phi_b_scf_8_re.cube $SCRATCH
cp /cluster/projects/nn4654k/ambr/zora/row5/calcs_gto/Nb_ano-r3_pbe_cubes/phi_b_scf_9_re.cube $SCRATCH
cd $SCRATCH
export OMP_NUM_THREADS=4
/cluster/home/ambr/software/mrchem/install_cubeparser/bin/mrchem --launcher 'srun -n 40' --json Nb_pbe

savefile Nb_pbe.out
savefile Nb_pbe.json

DIR=/cluster/projects/nn4654k/$(whoami)/MWOrbitals/${SLURM_JOBID}
mkdir -p $DIR
cp orbitals/* $DIR/
echo $DIR > ${SLURM_SUBMIT_DIR}/Nb_pbe.orbitals

DIR=/cluster/projects/nn4654k/$(whoami)/MWCheckpoints/${SLURM_JOBID}
mkdir -p $DIR
cp checkpoint/* $DIR/
echo $DIR > ${SLURM_SUBMIT_DIR}/Nb_pbe.checkpoint

exit 0