#! /bin/bash

#-------------------------------------------
# File generated 2021-05-07 14:33:09.994082
#-------------------------------------------

#SBATCH --account=nn9330k
#SBATCH --job-name=CO2
#SBATCH --output=CO2.log
#SBATCH --error=CO2.err
#SBATCH --nodes=6
#SBATCH --ntasks-per-node=8
#SBATCH --cpus-per-task=16
#SBATCH --time=60:00
#SBATCH --mail-type=NONE
#SBATCH --partition=normal

source /cluster/home/ambr/mrchem/tools/betzy.env
export OMP_NUM_THREADS=16

set -o errexit
set -o nounset

cp CO2.inp $SCRATCH

cd $SCRATCH
/cluster/home/ambr/mrchem/install-new-zora/bin/mrchem --launcher='mpirun -map-by ppr:1:numa -bind-to numa' CO2

savefile CO2.out
savefile CO2.json

mkdir -p /cluster/projects/${SLURM_JOB_ACCOUNT}/ambr/orbitals/${SLURM_JOBID}
cp orbitals/* /cluster/projects/${SLURM_JOB_ACCOUNT}/ambr/orbitals/${SLURM_JOBID}/
echo /cluster/projects/${SLURM_JOB_ACCOUNT}/ambr/orbitals/${SLURM_JOBID} > ${SLURM_SUBMIT_DIR}/CO2.orbitals

mkdir -p /cluster/projects/${SLURM_JOB_ACCOUNT}/ambr/checkpoints/${SLURM_JOBID}
cp checkpoint/* /cluster/projects/${SLURM_JOB_ACCOUNT}/ambr/checkpoints/${SLURM_JOBID}/
echo /cluster/projects/${SLURM_JOB_ACCOUNT}/ambr/checkpoints/${SLURM_JOBID} > ${SLURM_SUBMIT_DIR}/CO2.checkpoint

exit 0
