#! /bin/bash

#-------------------------------------------
# File generated 2021-05-07 14:52:03.734111
#-------------------------------------------

#SBATCH --account=nn9330k
#SBATCH --job-name=NiCO4
#SBATCH --output=NiCO4.log
#SBATCH --error=NiCO4.err
#SBATCH --nodes=10
#SBATCH --ntasks-per-node=8
#SBATCH --cpus-per-task=16
#SBATCH --time=3:00:00
#SBATCH --mail-type=NONE
#SBATCH --partition=normal

source /cluster/home/ambr/mrchem/tools/betzy.env
export OMP_NUM_THREADS=16

set -o errexit
set -o nounset

cp NiCO4.inp $SCRATCH

cd $SCRATCH
/cluster/home/ambr/mrchem/install-new-zora/bin/mrchem --launcher='mpirun -map-by ppr:1:numa -bind-to numa' NiCO4

savefile NiCO4.out
savefile NiCO4.json

mkdir -p /cluster/projects/${SLURM_JOB_ACCOUNT}/ambr/orbitals/${SLURM_JOBID}
cp orbitals/* /cluster/projects/${SLURM_JOB_ACCOUNT}/ambr/orbitals/${SLURM_JOBID}/
echo /cluster/projects/${SLURM_JOB_ACCOUNT}/ambr/orbitals/${SLURM_JOBID} > ${SLURM_SUBMIT_DIR}/NiCO4.orbitals

mkdir -p /cluster/projects/${SLURM_JOB_ACCOUNT}/ambr/checkpoints/${SLURM_JOBID}
cp checkpoint/* /cluster/projects/${SLURM_JOB_ACCOUNT}/ambr/checkpoints/${SLURM_JOBID}/
echo /cluster/projects/${SLURM_JOB_ACCOUNT}/ambr/checkpoints/${SLURM_JOBID} > ${SLURM_SUBMIT_DIR}/NiCO4.checkpoint

exit 0
