#! /bin/bash

#-------------------------------------------
# File generated 2021-05-07 14:33:17.073923
#-------------------------------------------

#SBATCH --account=nn9330k
#SBATCH --job-name=PH2OH
#SBATCH --output=PH2OH.log
#SBATCH --error=PH2OH.err
#SBATCH --nodes=6
#SBATCH --ntasks-per-node=8
#SBATCH --cpus-per-task=16
#SBATCH --time=60:00
#SBATCH --mail-type=NONE
#SBATCH --partition=normal

source /cluster/home/ambr/mrchem/tools/betzy.env
export OMP_NUM_THREADS=16

set -o errexit
set -o nounset

cp PH2OH.inp $SCRATCH

cd $SCRATCH
/cluster/home/ambr/mrchem/install-new-zora/bin/mrchem --launcher='mpirun -map-by ppr:1:numa -bind-to numa' PH2OH

savefile PH2OH.out
savefile PH2OH.json

mkdir -p /cluster/projects/${SLURM_JOB_ACCOUNT}/ambr/orbitals/${SLURM_JOBID}
cp orbitals/* /cluster/projects/${SLURM_JOB_ACCOUNT}/ambr/orbitals/${SLURM_JOBID}/
echo /cluster/projects/${SLURM_JOB_ACCOUNT}/ambr/orbitals/${SLURM_JOBID} > ${SLURM_SUBMIT_DIR}/PH2OH.orbitals

mkdir -p /cluster/projects/${SLURM_JOB_ACCOUNT}/ambr/checkpoints/${SLURM_JOBID}
cp checkpoint/* /cluster/projects/${SLURM_JOB_ACCOUNT}/ambr/checkpoints/${SLURM_JOBID}/
echo /cluster/projects/${SLURM_JOB_ACCOUNT}/ambr/checkpoints/${SLURM_JOBID} > ${SLURM_SUBMIT_DIR}/PH2OH.checkpoint

exit 0
